# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

# exec-once = $terminal
# exec-once = nm-applet &
exec-once = waybar & hyprpaper & hypridle
exec-once = hyprpm reload -n
exec-once = bash -lc 'test -f ~/.cache/hyprpm-vd-installed || (hyprpm update && hyprpm add https://github.com/levnikmyskin/hyprland-virtual-desktops && touch ~/.cache/hyprpm-vd-installed)'
exec-once = hyprpm enable virtual-desktops || true

