stickyrule = class:^(brave-teams.microsoft.com).*,2
plugin {
    virtual-desktops {
        names = 1:Coding PHP and JS, 2:Communicaion, 3:Coding Rust, 4:Research and Personal, 5:Scrathes
        cycleworkspaces = 1
        rememberlayout = size
        notifyinit = 0
        verbose_logging = 0
    }
}
