# See https://wiki.hypr.land/Configuring/Window-Rules/ for more
# See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

windowrule {
    # Ignore maximize requests from all apps. You'll probably like this.
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

# Hyprland-run windowrule
windowrule {
    name = move-hyprland-run

    match:class = hyprland-run

    move = 20 monitor_h-120
    float = yes
}

windowrule {
    name = general-opacity
    match:class = .*
    opacity = 1.00 0.96 
}

windowrule {
    name = ghostty-opacity
    match:class = ^com\.mitchellh\.ghostty$
    opacity = 0.93 override 0.80 override
}

windowrule {
    name = alacritty-opacity
    match:class = ^(Alacritty)$
    opacity = 0.93 override 0.80 override
}

windowrule {
    name = phpstorm-opacity
    match:class = ^(jetbrains-phpstorm)$
    opacity = 0.93 override 0.80 override
}

windowrule {
    name = remove-youtube-opacity
    match:title = ^(YouTube).*
    opacity = 1.0 override 1.0 override
}

windowrule {
    name = remove-firefox-pip-opacity
    match:title = Picture-in-Picture
    opacity = 1.0 override 1.0 override
}

windowrule {
    name = remove-pip-opacity
    match:title = Picture in picture
    opacity = 1.0 override 1.0 override
}


windowrule {
    name = centered-floating-window
    match:class = ^(centered_float_window)$
    
    float = yes
    size = 960 600
    center = yes
}

