name = "dev_menu"
name_pretty = "Dev Tools"
fixed_order = true

[[entries]]
text = "Apps & WebAPPs"
submenu = "dev_apps_menu"
icon = "/home/arch/.local/share/applications/icons/apps.svg"

[[entries]]
text = "Docker"
submenu = "dev_docker_menu"
icon = "/home/arch/.local/share/applications/icons/docker1.png"

[[entries]]
text = "TUIs"
submenu = "dev_tuis_menu"
icon = "/home/arch/.local/share/applications/icons/tuis.svg"

[[entries]]
text = "VPN"
submenu = "dev_vpn_menu"
icon = "/home/arch/.local/share/applications/icons/vpn.svg"
