name = "kr_menu"
name_pretty = "KodingRocks Menu"
icon = "bookmark"
fixed_order = true

[[entries]]
text = "Dev"
submenu = "dev_menu"

[[entries]]
text = "System"
submenu = "system_menu"

[[entries]]
text = "Setup"
submenu = "setup_menu"

[[entries]]
text = "Power Menu"
submenu = "power_menu"

[[entries]]
text = "Shortcuts"
submenu = "shortcuts_menu"

[[entries]]
text = "Screenshots"
submenu = "screenshots_menu"

# TODO: themes
