name = "setup_menu"
name_pretty = "Setup Menu"
icon = "bookmark"

[[entries]]
text = "Install WebAPP"
actions = { "install_webapp" = "alacritty --class centered_float_window -e webapp-install" }

[[entries]]
text = "Install TUI"
actions = { "install_tui" = "alacritty --class centered_float_window -e tui-install" }
#
# [[entries]]
# text = "Restart"
# actions = { "reboot" = "systemctl reboot" }
#
# [[entries]]
# text = "Shutdown"
# actions = { "shutdown" = "systemctl poweroff" }
#
