name = "setup_menu"
name_pretty = "Setup Menu"

[[entries]]
text = "Install WebAPP"
actions = { "install_webapp" = "alacritty --class centered_float_window -e webapp-install" }

[[entries]]
text = "Install TUI"
actions = { "install_tui" = "alacritty --class centered_float_window -e tui-install" }

[[entries]]
text = "Install Packages"
actions = { "install_packages" = "alacritty --class centered_float_window -e pkg-install" }

[[entries]]
text = "Install AUR"
actions = { "install_aur" = "alacritty --class centered_float_window -e pkg-aur-install" }
