name = "shortcuts_menu"
name_pretty = "Shortcuts Menu"
icon = "bookmark"
fixed_order = true

[[entries]]
text = "Hyprland Shortcuts"
actions = { "open_hypr_keybindings" = "walker -m menus:hypr_keybindings --minheight 1 -HN" }

[[entries]]
text = "Menus"
submenu = "hyprland_keybindings_menu"

[[entries]]
text = "APPs and WebAPPs"
submenu = "hyprland_keybindings_menu"

[[entries]]
text = "Neovim"
submenu = "nvim_shortcuts_summary"

[[entries]]
text = "Yazi"
submenu = "hyprland_keybindings_menu"

[[entries]]
text = "Terminal Commands"
submenu = "hyprland_keybindings_menu"
