name = "system_menu"
name_pretty = "System Menu"

[[entries]]
text = "System Monitor"
actions = { "system_monitor" = "alacritty --class centered_float_window -e btop" }
icon = "/home/arch/.local/share/applications/icons/health.svg"

[[entries]]
text = "Wifi and Network"
actions = { "wifi_network" = "alacritty --class centered_float_window -e impala" }
icon = "/home/arch/.local/share/applications/icons/home-wifi.svg"

[[entries]]
text = "Bluetooh"
actions = { "bluetooth" = "alacritty --class centered_float_window -e bluetui" }
icon = "/home/arch/.local/share/applications/icons/bluetooth-circle.svg"

[[entries]]
text = "Sound Controls"
actions = { "sound_controls" = "alacritty --class centered_float_window -e wiremix" }
icon = "/home/arch/.local/share/applications/icons/speaker.svg"
