# See https://wiki.hypr.land/Configuring/Window-Rules/ for more
# See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

# Example windowrule
# windowrule = float,class:^(kitty)$,title:^(kitty)$

# Ignore maximize requests from apps. You'll probably like this.
windowrule = suppressevent maximize, class:.*

windowrule = opacity 0.99 0.96, class:.*

# Fix some dragging issues with XWayland
windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0

# workspace = 1, persistent:true
# workspace = 2, persistent:true
# workspace = 3, persistent:true
# workspace = 4, persistent:true
# workspace = 5, persistent:true
# workspace = 6, persistent:true
# workspace = 7, persistent:true
# workspace = 8, persistent:true

# Adding rules to run calendar tui from waybar
windowrulev2 = float,class:^(centered_float_window)$
windowrulev2 = size 960 600,class:^(centered_float_window)$
windowrulev2 = center,class:^(centered_float_window)$
# windowrulev2 = opacity,class:^(Brave)$
windowrule = opacity 1.0,class:^(brave)$

