theme = "tokyo-night"
force_keyboard_focus = false    # forces keyboard forcus to stay in Walker
close_when_open = true          # close walker when invoking while already opened
click_to_close = true
# debug = true

[providers.actions]
"menus:config_files_menu" = [
  { action = "open", label = "Open", bind = "Return", default = true },
  { action = "open_float", label = "Open Float", bind = "ctrl Return" },
]
